name: html2pdf with puppeteer
description: Convert HTML to PDF using puppeteer
author: ntdesmond

inputs:
  path:
    description: "Path to HTML file, may include query parameters if needed"
    required: true

  output:
    description: "Output file path"
    required: true

  options:
    description: "options to page.pdf()"
    required: false
    default: "{}"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: file-text
  color: red
